version: '3.4'
networks:
  network:
    driver: bridge
    name: weatherapi-dev
services:
  weatherapi:
    image: "dirmans/weatherapi:1.0.0"
    container_name: weatherapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9000
    networks:
      - network